### ISSUE TITLE
关于项目的编译，代码同步

### ISSUE THREAD

**Issue by bylijian** [zengpeace/apprtcmobile#1]
作者你好，我在研究WebRtc的过程中看到了你的项目，非常好，直接运行，代码还很新。
我有个疑问，就是这个项目是怎么编译出来的，流程是什么，还有，官方更新了代码，你是如何同步的。网上这方面的新资料不多，或者你有空可以写个博客，写一下填坑的过程。

**Comment by zengpeace** [comment]
感谢你的肯定和支持，博客晚一点会写的。编译，主要是按照官网的步骤，也做什么特别的操作，个人觉得最大的障碍就是梯子吧，搞个好的梯子就好了。
